### ISSUE TITLE
Build Xubuntu vm for Windows students

### ISSUE THREAD

**Issue by zstumgoren** [stanfordjournalism/stanford-dj-vm#1]
Create a pre-provisioned Xubuntu VM for student use.

## Key Resources

*  [CIR's Xubuntu VM HOWTO](https://github.com/cirlabs/vm/blob/master/HOWTO.md)
* [CIR's bootsraph.sh](https://github.com/cirlabs/vm/blob/master/bootstrap.sh)

## Tasks

- [x] Create Xubuntu VM
- [x] Customize CIR's bootstraph.sh script to include only the necessary software, including:
   - [x] vim
   - [x] datakit installation
   - [x] [Atom.io](https://flight-manual.atom.io/getting-started/sections/installing-atom/#platform-linux)
   - [x] pipenv
   - [x] pip install csvkit
 - [x] Add bookmarks to FF
    - [x] Stanford Journalism GH
    - [x] Hitchhiker's Guide to Python
    - [x] Unix Shell tutorial and CLI cheatsheet
- [x] Create `configure_system.py` (#7)
- [x] Add README to desktop 
- [x] Export OVF file (#3)
